// Traditional character mapping for the most common Chinese characters
// This mapping covers characters that differ between simplified and traditional forms
export const TRADITIONAL_MAPPING: Record<string, string> = {
  // Common characters that differ between simplified and traditional
  '爱': '愛',
  '贝': '貝',
  '车': '車',
  '东': '東',
  '发': '發',
  '风': '風',
  '国': '國',
  '华': '華',
  '见': '見',
  '进': '進',
  '开': '開',
  '来': '來',
  '龙': '龍',
  '门': '門',
  '鸟': '鳥',
  '气': '氣',
  '让': '讓',
  '说': '說',
  '为': '為',
  '无': '無',
  '习': '習',
  '学': '學',
  '业': '業',
  '义': '義',
  '语': '語',
  '远': '遠',
  '这': '這',
  '种': '種',
  '钟': '鐘',
  '总': '總',
  '从': '從',
  '电': '電',
  '对': '對',
  '飞': '飛',
  '关': '關',
  '还': '還',
  '会': '會',
  '机': '機',
  '几': '幾',
  '间': '間',
  '将': '將',
  '经': '經',
  '觉': '覺',
  '乐': '樂',
  '历': '歷',
  '两': '兩',
  '吗': '嗎',
  '买': '買',
  '卖': '賣',
  '们': '們',
  '难': '難',
  '农': '農',
  '盘': '盤',
  '钱': '錢',
  '轻': '輕',
  '请': '請',
  '认': '認',
  '时': '時',
  '实': '實',
  '书': '書',
  '谁': '誰',
  '虽': '雖',
  '岁': '歲',
  '题': '題',
  '听': '聽',
  '头': '頭',
  '问': '問',
  '现': '現',
  '线': '線',
  '写': '寫',
  '谢': '謝',
  '兴': '興',
  '样': '樣',
  '药': '藥',
  '页': '頁',
  '应': '應',
  '组': '組',
  '边': '邊',
  '变': '變',
  '层': '層',
  '产': '產',
  '长': '長',
  '场': '場',
  '错': '錯',
  '当': '當',
  '动': '動',
  '读': '讀',
  '饿': '餓',
  '儿': '兒',
  '饭': '飯',
  '观': '觀',
  '过': '過',
  '号': '號',
  '红': '紅',
  '后': '後',
  '话': '話',
  '坏': '壞',
  '欢': '歡',
  '讲': '講',
  '课': '課',
  '里': '裡',
  '妈': '媽',
  '马': '馬',
  '面': '面',
  '鱼': '魚',
  '云': '雲',
  '张': '張',
};

/**
 * Get traditional character for a simplified character
 * @param simplified - The simplified Chinese character
 * @returns The traditional character, or the same character if no mapping exists
 */
export function getTraditionalCharacter(simplified: string): string {
  return TRADITIONAL_MAPPING[simplified] || simplified;
}

/**
 * Check if a character has a different traditional form
 * @param simplified - The simplified Chinese character
 * @returns True if the character has a different traditional form
 */
export function hasTraditionalForm(simplified: string): boolean {
  return TRADITIONAL_MAPPING[simplified] !== undefined;
} 
